name: Generate Images
on:
  schedule:
    - cron: "0 1 * * *"
  workflow_dispatch:

jobs:
  Main:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Checkout OnyxBay
        uses: actions/checkout@v2
        with:
          repository: ChaoticOnyx/OnyxBay
          ref: release/chaotic
          path: ./OnyxBay
      - name: Generate Images
        shell: pwsh
        env:
          TARGET_REPOSITORY: ./OnyxBay
        run: ./generate.ps1
      - name: Add & Commit
        uses: EndBug/add-and-commit@v7.5.0
        with:
          default_author: github_actions
